# Artificial Neural Network

### Importing the libraries

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

In [3]:
tf.__version__

'1.15.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [5]:
df = pd.read_csv('Churn_Modelling.csv')
x = df.iloc[:, 3:-1].values #we have to delete columns "RowNumber", "CustomerId", and "Surname" because they don'tgive us any valuable information.
y = df.iloc[:, -1].values

In [6]:
df

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [9]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [8]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

### Encoding categorical data

Label Encoding the "Gender" column

In [ ]:
#NOTE! There is no missing data, so we head over to "data encoding".

In [11]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:, 2])

In [12]:
x

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

One Hot Encoding the "Geography" column

In [ ]:
#We have to one-hot encoding (NOT label encoding) because there is no ordered relationship between "spain", "france", ...

In [16]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
x = np.array(ct.fit_transform(x))

In [17]:
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

### Splitting the dataset into the Training set and Test set

In [23]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [24]:
# x.shape
# x_train.shape

### Feature Scaling

In [ ]:
#NOTE! Feature scaling is COMULSORY for deep learning! so we have to do them in ANN problems. And it is so essential that we apply it to all the columns.

In [25]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler() #we don't have to put any arguments
x_train = sc.fit_transform(x_train) #since we want to apply it to all the columns, we write "x" (NOT x[...]).
x_test = sc.transform(x_test) # ~ 

## Part 2 - Building the ANN

### Initializing the ANN

In [27]:
#Using tensorflow for "Sequential" model.

from tensorflow.keras.models import Sequential

ann = Sequential()

### Adding the input layer and the first hidden layer

In [30]:
#Using the "Dense" class in tensorflow.

from tensorflow.keras.layers import Dense

ann.add(Dense(units = 6, activation = 'relu')) #Choosing the right number of "units" for the "Dense" layer is a work of an artist! Meaning, it is choosed only be experience, and NOT by a rule of thumb!
#activation = 'relu': rect function

### Adding the second hidden layer

In [31]:
ann.add(Dense(units = 6, activation = 'relu'))

### Adding the output layer

In [32]:
ann.add(Dense(units = 1, activation = 'sigmoid')) #units = 1: because we have binary outcome! If it was a 3-class output in the dataset (like: A, B, C), then we had to do "one-hot encoding" in the "encoding" section, and then choose "units = 3"! Since the one-hot encoded version in here becomes (100, 010, 001).
#activation = 'sigmoid': WE HAVE TO ALWAYS USE THIS FOR BINARY OUTCOME! If the outcome was not binary, WE HAD TO CHOOSE "softmax" function.

## Training the ANN

### Compiling the ANN

In [33]:
ann.compile(optimizer = 'Adam', loss = 'binary_crossentropy', metrics = ['accuracy']) #optimizer = 'Adam': does "Stocastic Gradient Descent"!
#loss = 'binary_crossentropy': WE HAVE TO ALWAYS USE THIS FOR BINARY OUTCOMES! If the outcome was not binary, WE HAD TO CHOOSE "categorical_crossentropy".

### Training the ANN on the Training set

In [34]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 100) #ALWAYS fit :DDD   
#batch_size = 32: for optimizing the performance of the model. "32" is the usual classic value.

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Train on 8000 samples
Epoch 1/100
8000/8000 [==============================] - 1s 68us/sample - loss: 0.7039 - acc: 0.5491
Epoch 2/100
8000/8000 [==============================] - 0s 54us/sample - loss: 0.4834 - acc: 0.7965
Epoch 3/100
8000/8000 [==============================] - 0s 58us/sample - loss: 0.4444 - acc: 0.8018
Epoch 4/100
8000/8000 [==============================] - 0s 55us/sample - loss: 0.4285 - acc: 0.8044
Epoch 5/100
8000/8000 [==============================] - 1s 72us/sample - loss: 0.4200 - acc: 0.8073
Epoch 6/100
8000/8000 [==============================] - 0s 45us/sample - loss: 0.4138 - acc: 0.8098
Epoch 7/100
8000/8000 [==============================] - 0s 48us/sample - loss: 0.4072 - acc: 0.8123
Epoch 8/100
8000/8000 [==============================] - 0s 50us/sample - loss: 0.4004 - acc: 0.

8000/8000 [==============================] - 0s 52us/sample - loss: 0.3368 - acc: 0.8635
Epoch 75/100
8000/8000 [==============================] - 0s 46us/sample - loss: 0.3365 - acc: 0.8631
Epoch 76/100
8000/8000 [==============================] - 0s 42us/sample - loss: 0.3371 - acc: 0.8631
Epoch 77/100
8000/8000 [==============================] - 0s 43us/sample - loss: 0.3366 - acc: 0.8627
Epoch 78/100
8000/8000 [==============================] - 0s 43us/sample - loss: 0.3362 - acc: 0.8636
Epoch 79/100
8000/8000 [==============================] - 0s 45us/sample - loss: 0.3366 - acc: 0.8654
Epoch 80/100
8000/8000 [==============================] - 0s 42us/sample - loss: 0.3368 - acc: 0.8631
Epoch 81/100
8000/8000 [==============================] - 0s 48us/sample - loss: 0.3364 - acc: 0.8639
Epoch 82/100
8000/8000 [==============================] - 1s 76us/sample - loss: 0.3362 - acc: 0.8641
Epoch 83/100
8000/8000 [==============================] - 0s 39us/sample - loss: 0.3362 - acc: 

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

#### Homework:

Using the above ANN model to predict if the costumer with the following informations will leave the bank:

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: $ 60000

Number of Products: 2

Does this costumer have a credit card? Yes

Is this costumer an Active Member?Yes

Estimated Salary: $ 50000

So, should we say goodbye to that costumer?

#### Solution:

In [36]:
ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))

array([[0.02934031]], dtype=float32)

In [40]:
#As we see above, the outcome is in the form of probability (LOG! Since we used the "sigmoid" function in the output layer, which returns the probability).
#Thus, we change the above probability to the real output "1" or "0" by " > 0.5"! (as the threshold probability) 

ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5

array([[False]])

Therefore, our ANN model predicts that this costumer stays in the bank!

<h4>Important Note 1:</h4> Any input of the ".predict()" method is a 2D array. Therefore, we should use two brackets "[[ ]]" to indicate that.

<h4>Important Note 2:</h4> Be aware to use the "sc.transform()".

### Predicting the Test set results

In [42]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), axis = 1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [44]:
from sklearn.metrics import accuracy_score, confusion_matrix

cm = confusion_matrix(y_test, y_pred)
ac = accuracy_score(y_test, y_pred)

print(cm)
print(ac)

[[1516   79]
 [ 199  206]]
0.861
